renew dockerfile script

diff --git a/Dockerfile.old b/Dockerfile.old
--- a/Dockerfile.old
+++ b/Dockerfile.old
@@ -33,46 +33,11 @@ COPY conf/ssl/* /etc/nginx/ssl/
 
 COPY start.sh /start.sh
 
-# Install PHP extensions dependencies FIRST
-RUN apk add --no-cache \
-    imap-dev \
-    krb5-dev \
-    libc-client \
-    libpng-dev \
-    libwebp-dev \
-    libjpeg-turbo-dev \
-    freetype-dev \
-    libxml2-dev \
-    postgresql-dev \
-    libzip-dev \
-    openldap-dev \
-    curl-dev \
-    icu-dev \
-    oniguruma-dev
+ENV PHP_MODULE_DEPS="gcc make libc-dev rabbitmq-c-dev zlib-dev libmemcached-dev cyrus-sasl-dev libpng-dev libxml2-dev krb5-dev curl-dev icu-dev libzip-dev openldap-dev imap-dev postgresql-dev libjpeg-turbo-dev freetype-dev libwebp-dev"
+# ENV MUSL_LOCALE_DEPS cmake make musl-dev gcc gettext-dev libintl 
+# ENV MUSL_LOCPATH /usr/share/i18n/locales/musl
 
-# Configure and install PHP extensions
-RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
-    docker-php-ext-configure imap --with-imap --with-imap-ssl && \
-    docker-php-ext-install \
-        exif \
-        sockets \
-        gd \
-        bcmath \
-        intl \
-        pcntl \
-        soap \
-        mysqli \
-        pdo \
-        pdo_mysql \
-        pgsql \
-        pdo_pgsql \
-        zip \
-        ldap \
-        imap \
-        dom \
-        opcache
-
-# nginx-1.28.0 (gunakan versi stable, bukan 1.29.3)
+# nginx-1.29.3
 ENV NGINX_VERSION=1.29.3
 ENV NJS_VERSION=0.9.4
 ENV PKG_RELEASE=1
@@ -80,6 +45,26 @@ ENV PKG_RELEASE=1
 RUN if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/dl-cdn.alpinelinux.org/'$APKMIRROR'/g' /etc/apk/repositories; fi \
     && set -x \
     && apk update \
+# add utf-8 locale support
+    # && apk add --no-cache $MUSL_LOCALE_DEPS \
+    # && wget https://gitlab.com/rilian-la-te/musl-locales/-/archive/master/musl-locales-master.zip \
+    # && unzip musl-locales-master.zip \
+    # && cd musl-locales-master \
+    # && cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install \
+    # && cd .. && rm -rf musl-locales-master* \
+# add locale support by glibc
+    # && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
+    # && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk \
+    # && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk \
+    # && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-i18n-2.35-r0.apk \
+    # && apk add --allow-untrusted glibc-2.35-r0.apk glibc-bin-2.35-r0.apk glibc-i18n-2.35-r0.apk \
+    # && /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8 \
+    # && rm -f *.apk \
+    # && echo "export PATH=/usr/glibc-compat/bin:$PATH" >> ~/.bashrc \
+# set default locale
+    # && echo "export LANG=en_US.UTF-8" >> ~/.bashrc \
+    # && echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc \
+# create nginx user/group first, to be consistent throughout docker variants
     && addgroup -g 101 -S nginx \
     && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
     && apkArch="$(cat /etc/apk/arch)" \
@@ -92,15 +77,32 @@ RUN if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/dl-cdn.alpin
     " \
     && case "$apkArch" in \
         x86_64|aarch64) \
-            # Install langsung dari Alpine repo (skip complex key verification)
-            apk add --no-cache $nginxPackages \
+# arches officially built by upstream
+            set -x \
+            && KEY_SHA512="de7031fdac1354096d3388d6f711a508328ce66c168967ee0658c294226d6e7a161ce7f2628d577d56f8b63ff6892cc576af6f7ef2a6aa2e17c62ff7b6bf0d98 *stdin" \
+            && apk add --no-cache --virtual .cert-deps \
+                openssl \
+            && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
+            && if [ "$(openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout | openssl sha512 -r)" = "$KEY_SHA512" ]; then \
+                echo "key verification succeeded!"; \
+                mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+            else \
+                echo "key verification failed!"; \
+                exit 1; \
+            fi \
+            && apk del .cert-deps \
+            && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
             ;; \
         *) \
-            # Build dari source untuk architecture lain
+# we're on an architecture upstream doesn't officially build for
+# let's build binaries from the published packaging sources
             set -x \
             && tempDir="$(mktemp -d)" \
             && chown nobody:nobody $tempDir \
             && apk add --no-cache --virtual .build-deps \
+                gcc \
+                libc-dev \
+                make \
                 openssl-dev \
                 pcre-dev \
                 zlib-dev \
@@ -111,7 +113,9 @@ RUN if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/dl-cdn.alpin
                 perl-dev \
                 libedit-dev \
                 mercurial \
+                bash \
                 alpine-sdk \
+                findutils \
             && su nobody -s /bin/sh -c " \
                 export HOME=${tempDir} \
                 && cd ${tempDir} \
@@ -121,13 +125,24 @@ RUN if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/dl-cdn.alpin
                 && cd alpine \
                 && make all \
                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
+                && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
                 " \
+            && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
+            && apk del .build-deps \
             && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages \
             ;; \
     esac \
+# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
+    && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
+    && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
+# Bring in gettext so we can get `envsubst`, then throw
+# the rest away. To do this, we need to install `gettext`
+# then move `envsubst` out of the way so `gettext` can
+# be deleted completely, then move `envsubst` back.
     && apk add --no-cache --virtual .gettext gettext \
     && mv /usr/bin/envsubst /tmp/ \
+    \
     && runDeps="$( \
         scanelf --needed --nobanner /tmp/envsubst \
             | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
@@ -138,7 +153,12 @@ RUN if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/dl-cdn.alpin
     && apk add --no-cache $runDeps \
     && apk del .gettext \
     && mv /tmp/envsubst /usr/local/bin/ \
-    && apk add --no-cache tzdata curl ca-certificates \
+# Bring in tzdata so users could set the timezones through the environment
+# variables
+    && apk add --no-cache tzdata \
+# Bring in curl and ca-certificates to make registering on DNS SD easier
+    && apk add --no-cache curl ca-certificates \
+# forward request and error logs to docker log collector
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log
 
@@ -166,44 +186,26 @@ RUN echo "cgi.fix_pathinfo=0" > ${php_vars} &&\
         -e "s/^;clear_env = no$/clear_env = no/" \
         ${fpm_conf} \
     && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
+    # && sed -i 's/session.save_handler = files/session.save_handler = redis\nsession.save_path = "tcp:\/\/redis:6379"/g' /usr/local/etc/php/php.ini
 
-# Install Composer dan PECL extensions
-RUN curl -sS http://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \
-    && apk add --no-cache \
-        libstdc++ \
-        mysql-client \
-        bash \
-        bash-completion \
-        shadow \
-        linux-headers \
-        supervisor \
-        git \
-        zip \
-        unzip \
-        coreutils \
-        libpng \
-        libmemcached-libs \
-        krb5-libs \
-        icu-libs \
-        icu \
-        c-client \
-        libzip \
-        openldap-clients \
-        imap \
-        postgresql-client \
-        postgresql-libs \
-        libcap \
-        tzdata \
-        sqlite \
-        lua-resty-core \
-        nginx-mod-http-lua \
-        rabbitmq-c \
+RUN curl http://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \
+    && apk add --no-cache libstdc++ mysql-client bash bash-completion shadow linux-headers \
+        supervisor git zip unzip coreutils libpng libmemcached-libs krb5-libs icu-libs \
+        icu c-client libzip openldap-clients imap postgresql-client postgresql-libs libcap tzdata sqlite \
+        lua-resty-core nginx-mod-http-lua rabbitmq-c \
     && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
-    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS \
+    && set -xe \
+    && apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
+    && apk add --no-cache --update --virtual .all-deps $PHP_MODULE_DEPS \
+    && docker-php-ext-configure gd --with-jpeg --with-freetype --with-webp \
+    && docker-php-ext-configure imap --with-imap --with-imap-ssl \
+    && docker-php-ext-configure pcntl --enable-pcntl \
+    && docker-php-ext-install exif sockets gd bcmath intl pcntl soap mysqli pdo pdo_mysql pgsql pdo_pgsql zip ldap imap dom opcache \
     && printf "\n\n" | pecl install amqp \
     && docker-php-ext-enable amqp \
     && printf "\n\n\n\n" | pecl install -o -f redis \
     && docker-php-ext-enable redis \
+    && docker-php-ext-enable sockets \
     && pecl install msgpack && docker-php-ext-enable msgpack \
     && pecl install igbinary && docker-php-ext-enable igbinary \
     && pecl install swoole && docker-php-ext-enable swoole \
@@ -212,10 +214,13 @@ RUN curl -sS http://getcomposer.org/installer | php -- --install-dir=/usr/bin/ -
     && pecl install mongodb \
     && docker-php-ext-enable mongodb \
     && rm -rf /tmp/pear \
-    && apk del .phpize-deps \
+    && apk del .all-deps .phpize-deps \
+    # && composer config -g repos.packagist composer https://mirrors.cloud.tencent.com/composer/ \
+    # && if [ "$COMPOSERMIRROR" != "" ]; then composer config -g repos.packagist composer ${COMPOSERMIRROR}; fi \
     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/* \
-    && rm -f /etc/nginx/conf.d/default.conf.apk-new /etc/nginx/nginx.conf.apk-new \
+    && rm -f /etc/nginx/conf.d/default.conf.apk-new && rm -f /etc/nginx/nginx.conf.apk-new \
     && if [ "$APKMIRROR" != "dl-cdn.alpinelinux.org" ]; then sed -i 's/'$APKMIRROR'/dl-cdn.alpinelinux.org/g' /etc/apk/repositories; fi \
+    && set -ex \
     && setcap 'cap_net_bind_service=+ep' /usr/local/bin/php \
     && mkdir -p /var/log/supervisor \
     && chmod +x /start.sh
